# ===================================
#  List Behavior Config
# ===================================
list: $/tiipiik/catalog/models/brand/columns.yaml
modelClass: Tiipiik\Catalog\Models\Brand
title: tiipiik.catalog::lang.config.list.brand_title
recordUrl: tiipiik/catalog/brands/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt