# ===================================
#  Form Behavior Config
# ===================================

name: tiipiik.catalog::lang.config.form.name
form: ~/plugins/tiipiik/catalog/models/product/fields.yaml
modelClass: Tiipiik\Catalog\Models\Product
defaultRedirect: tiipiik/catalog/products

create:
    title: tiipiik.catalog::lang.config.form.create_title
    redirect: tiipiik/catalog/products/update/:id
    redirectClose: tiipiik/catalog/products

update:
    title: tiipiik.catalog::lang.config.form.update_title
    redirect: tiipiik/catalog/products/update/:id
    redirectClose: tiipiik/catalog/products