# ===================================
# Filter Scope Definitions
# ===================================
scopes:
    category:
        # Filter name
        label: tiipiik.catalog::lang.products.category
        # Model Class name
        modelClass: Tiipiik\Catalog\Models\Category
        # Model attribute to display for the name
        nameFrom: name
        # Apply query scope
        scope: FilterCategories

    group:
        label: tiipiik.catalog::lang.config.form.group_name
        modelClass: Tiipiik\Catalog\Models\Group
        nameFrom: name
        scope: FilterGroups

    brand:
        label: tiipiik.catalog::lang.config.form.brand_name
        modelClass: Tiipiik\Catalog\Models\Brand
        nameFrom: name
        scope: FilterBrands