# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: tiipiik.catalog::lang.config.form.store_name

# Model Form Field configuration
form: $/tiipiik/catalog/models/store/fields.yaml

# Model Class name
modelClass: Tiipiik\Catalog\Models\Store

# Default redirect location
defaultRedirect: tiipiik/catalog/stores

# Create page
create:
    title: tiipiik.catalog::lang.config.form.store_create_title
    redirect: tiipiik/catalog/stores/update/:id
    redirectClose: tiipiik/catalog/stores

# Update page
update:
    title: tiipiik.catalog::lang.config.form.store_update_title
    redirect: tiipiik/catalog/stores
    redirectClose: tiipiik/catalog/stores